/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import Controller.Employee;
import Model.Calculates;
import Model.Ordenamiento;

/**
 *
 * @author juanm
 */
public class Interface extends javax.swing.JFrame {

    private int index = 0;
    private Employee[] data = new Employee[100];
    Calculates ObjM = new Calculates();
    Ordenamiento ObjOrd = new Ordenamiento();
    DefaultTableModel ModelTable = new DefaultTableModel();

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
        for(int i = 0; i < 100; i++){
            data[i] = new Employee();
        }
        String ids[] = {"ID", "Name", "Days Worked", "E.Day", "E.Night", "E.Sunday", "SBMA", "Net"};
        ModelTable.setColumnIdentifiers(ids);

        JTableHeader he = tableData.getTableHeader();
        he.setFont(new java.awt.Font("Tahoma", 1, 15));
        tableData.setModel(ModelTable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        p_Menu = new javax.swing.JPanel();
        b_Create = new manulibrary.buttonPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b_Read = new manulibrary.buttonPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_Update = new manulibrary.buttonPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_Delete = new manulibrary.buttonPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panels = new javax.swing.JTabbedPane();
        p_Create = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        btn_Next = new javax.swing.JButton();
        I_ExtSun = new javax.swing.JTextField();
        I_ExtNig = new javax.swing.JTextField();
        I_ExtDay = new javax.swing.JTextField();
        I_DaysW = new javax.swing.JTextField();
        I_Salary = new javax.swing.JTextField();
        I_ZodSig = new javax.swing.JComboBox<>();
        aN = new javax.swing.JRadioButton();
        abN = new javax.swing.JRadioButton();
        bN = new javax.swing.JRadioButton();
        oN = new javax.swing.JRadioButton();
        oP = new javax.swing.JRadioButton();
        abP = new javax.swing.JRadioButton();
        bP = new javax.swing.JRadioButton();
        aP = new javax.swing.JRadioButton();
        I_Disctrict = new javax.swing.JComboBox<>();
        I_Mun = new javax.swing.JTextField();
        E_ExpID = new javax.swing.JTextField();
        I_BritDep = new javax.swing.JComboBox<>();
        I_Div = new javax.swing.JComboBox<>();
        I_Sec = new javax.swing.JComboBox<>();
        I_Dep = new javax.swing.JComboBox<>();
        txt_EmpTy = new javax.swing.JComboBox<>();
        I_BrttDa = new com.toedter.calendar.JDateChooser();
        jLabel32 = new javax.swing.JLabel();
        I_ID = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        I_Name = new javax.swing.JTextField();
        p_Read = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableData = new javax.swing.JTable();
        p_Delete = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Delete = new javax.swing.JTextArea();
        jLabel30 = new javax.swing.JLabel();
        I_IDDelete = new javax.swing.JTextField();
        btn_Delete = new manulibrary.buttonPanel();
        jLabel31 = new javax.swing.JLabel();
        p_Update = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Update = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        I_IDUpdate = new javax.swing.JTextField();
        I_ValueUpdate = new javax.swing.JTextField();
        btn_Update = new manulibrary.buttonPanel();
        jLabel29 = new javax.swing.JLabel();
        I_AtributeUpdate = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_Menu.setBackground(new java.awt.Color(44, 47, 51));
        p_Menu.setLayout(new java.awt.GridBagLayout());

        b_Create.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Create.setBorderWidth(5);
        b_Create.setCornerRadius(70);
        b_Create.setEndColor(new java.awt.Color(251, 46, 0));
        b_Create.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Create.setStartColor(new java.awt.Color(187, 0, 163));
        b_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_CreateMouseClicked(evt);
            }
        });
        b_Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create");
        b_Create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("+100 emplyees added");
        b_Create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Create, gridBagConstraints);

        b_Read.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Read.setBorderWidth(5);
        b_Read.setCornerRadius(70);
        b_Read.setEndColor(new java.awt.Color(251, 46, 0));
        b_Read.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Read.setStartColor(new java.awt.Color(187, 0, 163));
        b_Read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ReadMouseClicked(evt);
            }
        });
        b_Read.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Know your employees");
        b_Read.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Read");
        b_Read.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Read, gridBagConstraints);

        b_Update.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Update.setBorderWidth(5);
        b_Update.setCornerRadius(70);
        b_Update.setEndColor(new java.awt.Color(251, 46, 0));
        b_Update.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Update.setStartColor(new java.awt.Color(187, 0, 163));
        b_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_UpdateMouseClicked(evt);
            }
        });
        b_Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("+1000 data avalible");
        b_Update.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update");
        b_Update.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Update, gridBagConstraints);

        b_Delete.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Delete.setBorderWidth(5);
        b_Delete.setCornerRadius(70);
        b_Delete.setEndColor(new java.awt.Color(251, 46, 0));
        b_Delete.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Delete.setStartColor(new java.awt.Color(187, 0, 163));
        b_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_DeleteMouseClicked(evt);
            }
        });
        b_Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Delete inactive");
        b_Delete.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete");
        b_Delete.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Delete, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carrefurgas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 26, 0);
        p_Menu.add(jLabel1, gridBagConstraints);

        getContentPane().add(p_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 720));

        panels.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        p_Create.setBackground(new java.awt.Color(35, 39, 42));
        p_Create.setLayout(new java.awt.GridBagLayout());

        jLabel10.setBackground(new java.awt.Color(240, 243, 255));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(240, 243, 255));
        jLabel10.setText("Employee type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel10, gridBagConstraints);

        jLabel11.setBackground(new java.awt.Color(240, 243, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(240, 243, 255));
        jLabel11.setText("Department");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel11, gridBagConstraints);

        jLabel12.setBackground(new java.awt.Color(240, 243, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(240, 243, 255));
        jLabel12.setText("Section");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel12, gridBagConstraints);

        jLabel13.setBackground(new java.awt.Color(240, 243, 255));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(240, 243, 255));
        jLabel13.setText("Division");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel13, gridBagConstraints);

        jLabel14.setBackground(new java.awt.Color(240, 243, 255));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(240, 243, 255));
        jLabel14.setText("Brithdate");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel14, gridBagConstraints);

        jLabel15.setBackground(new java.awt.Color(240, 243, 255));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(240, 243, 255));
        jLabel15.setText("Departament");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel15, gridBagConstraints);

        jLabel16.setBackground(new java.awt.Color(240, 243, 255));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(240, 243, 255));
        jLabel16.setText("Identification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel16, gridBagConstraints);

        jLabel17.setBackground(new java.awt.Color(240, 243, 255));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(240, 243, 255));
        jLabel17.setText("Municipality");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel17, gridBagConstraints);

        jLabel18.setBackground(new java.awt.Color(240, 243, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(240, 243, 255));
        jLabel18.setText("District");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel18, gridBagConstraints);

        jLabel19.setBackground(new java.awt.Color(240, 243, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(240, 243, 255));
        jLabel19.setText("Blood Type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel19, gridBagConstraints);

        jLabel20.setBackground(new java.awt.Color(240, 243, 255));
        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(240, 243, 255));
        jLabel20.setText("Zodiac Sign");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel20, gridBagConstraints);

        jLabel21.setBackground(new java.awt.Color(240, 243, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(240, 243, 255));
        jLabel21.setText("Salary");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel21, gridBagConstraints);

        jLabel22.setBackground(new java.awt.Color(240, 243, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(240, 243, 255));
        jLabel22.setText("Days worked");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel22, gridBagConstraints);

        jLabel23.setBackground(new java.awt.Color(240, 243, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(240, 243, 255));
        jLabel23.setText("Daytime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel23, gridBagConstraints);

        jLabel24.setBackground(new java.awt.Color(240, 243, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(240, 243, 255));
        jLabel24.setText("Night");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel24, gridBagConstraints);

        jLabel25.setBackground(new java.awt.Color(240, 243, 255));
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(240, 243, 255));
        jLabel25.setText("Sundays");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel25, gridBagConstraints);

        btn_Next.setBackground(new java.awt.Color(21, 245, 186));
        btn_Next.setFont(new java.awt.Font("Yu Gothic", 1, 18)); // NOI18N
        btn_Next.setText("Next");
        btn_Next.setBorder(null);
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 90;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.insets = new java.awt.Insets(7, 7, 7, 7);
        p_Create.add(btn_Next, gridBagConstraints);

        I_ExtSun.setBackground(new java.awt.Color(49, 41, 102));
        I_ExtSun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_ExtSun.setForeground(new java.awt.Color(240, 243, 255));
        I_ExtSun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_ExtSun.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_ExtSun, gridBagConstraints);

        I_ExtNig.setBackground(new java.awt.Color(49, 41, 102));
        I_ExtNig.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_ExtNig.setForeground(new java.awt.Color(240, 243, 255));
        I_ExtNig.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_ExtNig.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_ExtNig, gridBagConstraints);

        I_ExtDay.setBackground(new java.awt.Color(49, 41, 102));
        I_ExtDay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_ExtDay.setForeground(new java.awt.Color(240, 243, 255));
        I_ExtDay.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_ExtDay.setPreferredSize(new java.awt.Dimension(220, 24));
        I_ExtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                I_ExtDayActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_ExtDay, gridBagConstraints);

        I_DaysW.setBackground(new java.awt.Color(49, 41, 102));
        I_DaysW.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_DaysW.setForeground(new java.awt.Color(240, 243, 255));
        I_DaysW.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_DaysW.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_DaysW, gridBagConstraints);

        I_Salary.setBackground(new java.awt.Color(49, 41, 102));
        I_Salary.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Salary.setForeground(new java.awt.Color(240, 243, 255));
        I_Salary.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_Salary.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Salary, gridBagConstraints);

        I_ZodSig.setBackground(new java.awt.Color(33, 25, 81));
        I_ZodSig.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_ZodSig.setForeground(new java.awt.Color(240, 243, 255));
        I_ZodSig.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Aries", "2. Tauro", "3. Géminis", "4. Cáncer", "5. Leo", "6. Virgo", "7. Libra", "8. Escorpión", "9. Sagitario", "10. Capricornio", "11. Acuario", "12. Piscis" }));
        I_ZodSig.setFocusable(false);
        I_ZodSig.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_ZodSig, gridBagConstraints);

        aN.setBackground(new java.awt.Color(33, 25, 81));
        aN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aN.setForeground(new java.awt.Color(240, 243, 255));
        aN.setText("A-");
        aN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(aN, gridBagConstraints);

        abN.setBackground(new java.awt.Color(33, 25, 81));
        abN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        abN.setForeground(new java.awt.Color(240, 243, 255));
        abN.setText("AB-");
        abN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(abN, gridBagConstraints);

        bN.setBackground(new java.awt.Color(33, 25, 81));
        bN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bN.setForeground(new java.awt.Color(240, 243, 255));
        bN.setText("B-");
        bN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(bN, gridBagConstraints);

        oN.setBackground(new java.awt.Color(33, 25, 81));
        oN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oN.setForeground(new java.awt.Color(240, 243, 255));
        oN.setText("O-");
        oN.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(oN, gridBagConstraints);

        oP.setBackground(new java.awt.Color(33, 25, 81));
        oP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        oP.setForeground(new java.awt.Color(240, 243, 255));
        oP.setText("O+");
        oP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(oP, gridBagConstraints);

        abP.setBackground(new java.awt.Color(33, 25, 81));
        abP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        abP.setForeground(new java.awt.Color(240, 243, 255));
        abP.setText("AB+");
        abP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(abP, gridBagConstraints);

        bP.setBackground(new java.awt.Color(33, 25, 81));
        bP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bP.setForeground(new java.awt.Color(240, 243, 255));
        bP.setText("B+");
        bP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(bP, gridBagConstraints);

        aP.setBackground(new java.awt.Color(33, 25, 81));
        aP.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        aP.setForeground(new java.awt.Color(240, 243, 255));
        aP.setText("A+");
        aP.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        aP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aPActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(aP, gridBagConstraints);

        I_Disctrict.setBackground(new java.awt.Color(33, 25, 81));
        I_Disctrict.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Disctrict.setForeground(new java.awt.Color(240, 243, 255));
        I_Disctrict.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aida Lucía", "Las Américas", "El Valencia", "El Recuerdo", "El Bosque", "San José", "El Lido", "Santa Clara", "El Encanto", "San Fernando", "San Camilo", "La Floresta", "Los Alamos", "Ciudad Jardín", "El Mirador", "La Esmeralda", "La Paz", "El Paraíso", "La Pradera", "El Palmar", "La Estrella", "Los Pinos", "La Primavera", "La Aurora", "La Castellana", "El Recreo", "El Paraíso", "San Francisco", "El Verge" }));
        I_Disctrict.setFocusable(false);
        I_Disctrict.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Disctrict, gridBagConstraints);

        I_Mun.setBackground(new java.awt.Color(49, 41, 102));
        I_Mun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Mun.setForeground(new java.awt.Color(240, 243, 255));
        I_Mun.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_Mun.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Mun, gridBagConstraints);

        E_ExpID.setBackground(new java.awt.Color(49, 41, 102));
        E_ExpID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        E_ExpID.setForeground(new java.awt.Color(240, 243, 255));
        E_ExpID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        E_ExpID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        E_ExpID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        E_ExpID.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(E_ExpID, gridBagConstraints);

        I_BritDep.setBackground(new java.awt.Color(33, 25, 81));
        I_BritDep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_BritDep.setForeground(new java.awt.Color(240, 243, 255));
        I_BritDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Amazonas", "2. Antioquia", "3. Arauca", "4. Atlántico", "5. Bolívar", "6. Boyacá", "7. Caldas", "8. Caquetá", "9. Casanare", "10. Cauca", "11. Cesar", "12. Chocó", "13. Córdoba", "14. Cundinamarca", "15. Guainía", "16. Guaviare", "17. Huila", "18. La Guajira", "19. Magdalena", "20. Meta", "21. Nariño", "22. Norte de Santander", "23. Putumayo", "24. Quindio", "25. Risaralda", "26. San Andrés y Providencia", "27. Santander", "28. Sucre", "29. Tolima", "30. Valle del Cauca", "31. Vaupés", "32. Vichada" }));
        I_BritDep.setFocusable(false);
        I_BritDep.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_BritDep, gridBagConstraints);

        I_Div.setBackground(new java.awt.Color(33, 25, 81));
        I_Div.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Div.setForeground(new java.awt.Color(240, 243, 255));
        I_Div.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Insumos", "2. Repuestos", "3. Herramientas manuales", "4. Herramientas electromecánicas" }));
        I_Div.setFocusable(false);
        I_Div.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Div, gridBagConstraints);

        I_Sec.setBackground(new java.awt.Color(33, 25, 81));
        I_Sec.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Sec.setForeground(new java.awt.Color(240, 243, 255));
        I_Sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Electrodomésticos", "2. Gaseodomésticos", "3. Papelería", "4. Libros", "5. Juguetería", "6. Deportes", "7. Ropa deportiva hombre", "8. Ropa casual hombre", "9. Ropa deportiva dama", "10. Ropa casual dama", "11. Ropa deportiva niños y niñas", "12. Ropa casual niños y niñas", "13. Ropa bebés", "14. Ropa interior caballeros", "15. Ropa interior damas", "16. Granos y abarrotes", "17. Enlatados", "18. Vinos y licores", "19. Carnes", "20. Carnes frías", "21. Charcutería", "22. Lácteos", "23. Aseo hogar", "24. Aseo personal", "25. Cosméticos", "26. Ropa de cama", "27. Utensilios de cocina", "28. Ferretería", "29. Souvenirs", "30. Zapatería" }));
        I_Sec.setFocusable(false);
        I_Sec.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Sec, gridBagConstraints);

        I_Dep.setBackground(new java.awt.Color(33, 25, 81));
        I_Dep.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Dep.setForeground(new java.awt.Color(240, 243, 255));
        I_Dep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Administración", "2. Publicidad y mercadeo", "3. Ventas", "4. Mantenimiento", "5. Bodega", "6. Transporte", "7. Servicios generales", "8. Sistemas" }));
        I_Dep.setToolTipText("");
        I_Dep.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I_Dep.setFocusable(false);
        I_Dep.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Dep, gridBagConstraints);

        txt_EmpTy.setBackground(new java.awt.Color(33, 25, 81));
        txt_EmpTy.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_EmpTy.setForeground(new java.awt.Color(240, 243, 255));
        txt_EmpTy.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1. Fijo", "2. Temporal", "3. Cooperativa" }));
        txt_EmpTy.setToolTipText("");
        txt_EmpTy.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_EmpTy.setFocusable(false);
        txt_EmpTy.setPreferredSize(new java.awt.Dimension(220, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(txt_EmpTy, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(1, 1, 1, 1);
        p_Create.add(I_BrttDa, gridBagConstraints);

        jLabel32.setBackground(new java.awt.Color(240, 243, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(240, 243, 255));
        jLabel32.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel32, gridBagConstraints);

        I_ID.setBackground(new java.awt.Color(49, 41, 102));
        I_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_ID.setForeground(new java.awt.Color(240, 243, 255));
        I_ID.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_ID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I_ID.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        I_ID.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_ID, gridBagConstraints);

        jLabel33.setBackground(new java.awt.Color(240, 243, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(240, 243, 255));
        jLabel33.setText("Expedition Id");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 15);
        p_Create.add(jLabel33, gridBagConstraints);

        I_Name.setBackground(new java.awt.Color(49, 41, 102));
        I_Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        I_Name.setForeground(new java.awt.Color(240, 243, 255));
        I_Name.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(21, 245, 186), 1, true));
        I_Name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        I_Name.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        I_Name.setPreferredSize(new java.awt.Dimension(220, 24));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Create.add(I_Name, gridBagConstraints);

        panels.addTab("tab1", p_Create);

        p_Read.setBackground(new java.awt.Color(35, 39, 42));
        p_Read.setLayout(new java.awt.GridBagLayout());

        jScrollPane3.setPreferredSize(new java.awt.Dimension(650, 402));

        tableData.setBackground(new java.awt.Color(153, 170, 181));
        tableData.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(114, 137, 218), 5, true));
        tableData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        tableData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableData.setRowHeight(40);
        tableData.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableData.setShowGrid(false);
        jScrollPane3.setViewportView(tableData);

        p_Read.add(jScrollPane3, new java.awt.GridBagConstraints());

        panels.addTab("tab2", p_Read);

        p_Delete.setBackground(new java.awt.Color(35, 39, 42));
        p_Delete.setLayout(new java.awt.GridBagLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(400, 500));

        txt_Delete.setEditable(false);
        txt_Delete.setBackground(new java.awt.Color(44, 47, 51));
        txt_Delete.setColumns(20);
        txt_Delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Delete.setForeground(new java.awt.Color(255, 255, 255));
        txt_Delete.setRows(5);
        txt_Delete.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(114, 137, 218), 1, true), "Output Delete", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(114, 137, 218))); // NOI18N
        jScrollPane2.setViewportView(txt_Delete);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Delete.add(jScrollPane2, gridBagConstraints);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Identification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Delete.add(jLabel30, gridBagConstraints);

        I_IDDelete.setColumns(15);
        I_IDDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                I_IDDeleteKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Delete.add(I_IDDelete, gridBagConstraints);

        btn_Delete.setBorderColor(new java.awt.Color(254, 255, 255));
        btn_Delete.setBorderWidth(5);
        btn_Delete.setCornerRadius(50);
        btn_Delete.setEndColor(new java.awt.Color(255, 51, 51));
        btn_Delete.setPreferredSize(new java.awt.Dimension(150, 70));
        btn_Delete.setStartColor(new java.awt.Color(204, 0, 153));
        btn_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_DeleteMouseClicked(evt);
            }
        });
        btn_Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Delete");
        btn_Delete.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 50));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 4, 4, 4);
        p_Delete.add(btn_Delete, gridBagConstraints);

        panels.addTab("tab4", p_Delete);

        p_Update.setBackground(new java.awt.Color(35, 39, 42));
        p_Update.setLayout(new java.awt.GridBagLayout());

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 500));

        txt_Update.setEditable(false);
        txt_Update.setBackground(new java.awt.Color(44, 47, 51));
        txt_Update.setColumns(20);
        txt_Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_Update.setForeground(new java.awt.Color(255, 255, 255));
        txt_Update.setRows(5);
        txt_Update.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(114, 137, 218), 1, true), "Output Update", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(114, 137, 218))); // NOI18N
        jScrollPane1.setViewportView(txt_Update);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(jScrollPane1, gridBagConstraints);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Identification");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(jLabel26, gridBagConstraints);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Value to Update");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(jLabel27, gridBagConstraints);

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("New Value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(jLabel28, gridBagConstraints);

        I_IDUpdate.setColumns(15);
        I_IDUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                I_IDUpdateKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                I_IDUpdateKeyReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(I_IDUpdate, gridBagConstraints);

        I_ValueUpdate.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(I_ValueUpdate, gridBagConstraints);

        btn_Update.setBorderColor(new java.awt.Color(204, 204, 204));
        btn_Update.setBorderWidth(5);
        btn_Update.setCornerRadius(50);
        btn_Update.setEndColor(new java.awt.Color(0, 110, 140));
        btn_Update.setPreferredSize(new java.awt.Dimension(150, 70));
        btn_Update.setStartColor(new java.awt.Color(0, 0, 124));
        btn_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_UpdateMouseClicked(evt);
            }
        });
        btn_Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Update");
        btn_Update.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 120, 70));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        p_Update.add(btn_Update, gridBagConstraints);

        I_AtributeUpdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Days Worked", "Extra Day", "Extra Night", "Extra Sunday", "SBMA", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        p_Update.add(I_AtributeUpdate, gridBagConstraints);

        panels.addTab("tab3", p_Update);

        getContentPane().add(panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 730, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_CreateMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(0);
        ClearButtons();
        b_Create.setBorderWidth(5);
    }//GEN-LAST:event_b_CreateMouseClicked

    private void b_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_UpdateMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(3);
        ClearButtons();
        b_Update.setBorderWidth(5);
        txt_Update.setText("");
    }//GEN-LAST:event_b_UpdateMouseClicked

    private void b_ReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ReadMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(1);
        ClearButtons();
        b_Read.setBorderWidth(5);

        while (ModelTable.getRowCount() > 0) {
            ModelTable.removeRow(0);
        }
        

        Employee[] EmpOrd = ObjOrd.Ordenar(data, index);

        for(int i = 0; i < index; i++){
            Object[] dataToTable = { EmpOrd[i].getID(), EmpOrd[i].getName(), EmpOrd[i].getJA_DayW_47(),
                EmpOrd[i].getJA_ExtrD_47(), EmpOrd[i].getJA_ExtrN_47(), EmpOrd[i].getJA_ExtrS(),
                EmpOrd[i].getJA_SBMA_47(), EmpOrd[i].getJA_Net_47()
            };

            ModelTable.addRow(dataToTable);
            System.out.println("Filas: " + ModelTable.getRowCount());
        }
    }//GEN-LAST:event_b_ReadMouseClicked

    private void b_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_DeleteMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(2);
        ClearButtons();
        b_Delete.setBorderWidth(5);
        txt_Delete.setText("");
    }//GEN-LAST:event_b_DeleteMouseClicked

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        // 
        int BloodType;
        if(aP.isSelected()){
            BloodType = 1;
        }else if(aN.isSelected()){
            BloodType = 2;
        }else if(bP.isSelected()){
            BloodType = 3;
        }else if(bN.isSelected()){
            BloodType = 4;
        }else if(abP.isSelected()){
            BloodType = 5;
        }else if(abN.isSelected()){
            BloodType = 6;
        }else if(oP.isSelected()){
            BloodType = 7;
        }else if(oN.isSelected()){
            BloodType = 1;
        }else{
            BloodType = 0;
        }
        
        boolean FlasState = false;//Variable que va a almacenar true si los datos estan correctos
            try{
                if(I_BrttDa.getDate() == null|| I_Mun.getText().isEmpty() || E_ExpID.getText().isEmpty()|| (BloodType == 0)){
                    //Error in inputs (Clean inputs)
                    JOptionPane.showMessageDialog(this, "Ningun capo debe estar vacio. \n Ingresa de nuevo los datos.");
                }else if(Double.parseDouble(I_Salary.getText()) < 800){
                    JOptionPane.showMessageDialog(this, "El salario debe ser mayor o igual al SMLV");
                }else if(Double.parseDouble(I_DaysW.getText())<1 && Double.parseDouble(I_DaysW.getText())>15){
                    JOptionPane.showMessageDialog(this, "Los dias trabajados deben estar entre 1 y 15");
                }else if(Integer.parseInt(I_ExtDay.getText()) < 0 && Integer.parseInt(I_ExtDay.getText()) > 20){
                    JOptionPane.showMessageDialog(this, "Las horas extras diurnas deben estar entre 0 y 20");
                }else if(Integer.parseInt(I_ExtNig.getText()) < 0 && Integer.parseInt(I_ExtNig.getText()) > 30){
                    JOptionPane.showMessageDialog(this, "Las horas extras nocturnas deben estar entre 0 y 30");
                }else if(Integer.parseInt(I_ExtSun.getText()) < 0 && Integer.parseInt(I_ExtSun.getText())> 40){
                    JOptionPane.showMessageDialog(this, "Las horas extras dominicales deben estar entre 0 y 40");
                }else{
                    FlasState = true;
                }
            }catch(NumberFormatException e){
                //Esto se ejecuta si hay un error de tipo NumberFormatException
                JOptionPane.showMessageDialog(this, "Error en al ingresar los datos \n" + e.getMessage() + "\n Ingresa de nuevo los datos.");
                System.out.println("Error" + e.getMessage());
            }
        //Se hace un if con la variable FlagState para 
        //Settear los datos si todos estan dentro de los parametros
    if(FlasState){
        //Setteo de datos
        data[index].setID(Integer.parseInt(I_ID.getText()));
        data[index].setName(I_Name.getText());
        data[index].setJA_EmplTy_47(txt_EmpTy.getSelectedIndex() + 1);
        data[index].setJA_WorkDep_47(I_Dep.getSelectedIndex() + 1);
        data[index].setDateTimeJA_BrithDate_47(I_BrttDa.getDate());
        data[index].setJA_BrithDep_47(I_BritDep.getSelectedIndex() + 1);
        data[index].setJA_ExpID_47(E_ExpID.getText());
        data[index].setJA_Mun_47(I_Mun.getText());
        data[index].setJA_District(String.valueOf(I_Disctrict.getSelectedItem()));
        data[index].setJA_BloodTy_47(BloodType);
        data[index].setJA_ZodiSign_47(I_ZodSig.getSelectedIndex() + 1);
        data[index].setJA_SBMA_47(Double.parseDouble(I_Salary.getText()));
        data[index].setJA_DayW_47(Integer.parseInt(I_DaysW.getText()));
        data[index].setJA_ExtrD_47(Integer.parseInt(I_ExtDay.getText()));
        data[index].setJA_ExtrN_47(Integer.parseInt(I_ExtNig.getText()));
        data[index].setJA_ExtrS(Integer.parseInt(I_ExtSun.getText()));

        if(I_Dep.getSelectedIndex() == 2){
            data[index].setJA_Sec_47(I_Sec.getSelectedIndex() +1);
            if(I_Sec.getSelectedIndex() == 27){
                data[index].setJA_Div_47(I_Div.getSelectedIndex() +1);
            }
        }
            
        SendValues();
        System.out.println("Emplado añadido!: " + data[index].getID());
        index++;
    }
    }//GEN-LAST:event_btn_NextActionPerformed

    private void I_ExtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_I_ExtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_I_ExtDayActionPerformed

    private void aPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aPActionPerformed

    private void btn_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_UpdateMouseClicked
        // TODO add your handling code here:
        int ID = Integer.parseInt(I_IDUpdate.getText());
        String Value = I_ValueUpdate.getText();

        for(int i = 0; i < index; i++){
            if(data[i].getID() == ID){
                switch (I_AtributeUpdate.getSelectedIndex()) {
                    case 0:
                        data[i].setName(Value);
                        break;

                    case 1:
                        data[i].setJA_DayW_47(Integer.parseInt(Value));
                        break;

                    case 2:
                        data[i].setJA_ExtrD_47(Integer.parseInt(Value));
                        break;

                    case 3:
                        data[i].setJA_ExtrN_47(Integer.parseInt(Value));
                        break;

                    case 4:
                        data[i].setJA_ExtrS(Integer.parseInt(Value));
                        break;

                    case 5:
                        data[i].setJA_SBMA_47(Double.parseDouble(Value));
                        break;
                
                    default:
                        break;
                }
                txt_Update.append("\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
                txt_Update.append("\nValue update sucessful");
                ShowValues(data[i], txt_Update);
                JOptionPane.showMessageDialog(null, 
                    "Successful Update", 
                    "Information", 
                    JOptionPane.INFORMATION_MESSAGE
                );
                break;
            }
        }
    }//GEN-LAST:event_btn_UpdateMouseClicked

    private void btn_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_DeleteMouseClicked
        // TODO add your handling code here:
        int ID = Integer.parseInt(I_IDDelete.getText());
        Employee TemObj[] = new Employee[100];

        for(int i = 0; i < 100; i++){
            if(data[i].getID() != ID){
                TemObj[i] = data[i];
            }
        }   

        data = TemObj;

        JOptionPane.showMessageDialog(null, 
            "The employee was eliminated", 
            "Information", 
            JOptionPane.INFORMATION_MESSAGE
        );

        
    }//GEN-LAST:event_btn_DeleteMouseClicked

    private void I_IDDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_I_IDDeleteKeyPressed
        // TODO add your handling code here:
        try {
            int ID = Integer.parseInt(I_IDDelete.getText());
            for(int i = 0; i < index; i++){
                if(data[i].getID() == ID){
                    txt_Update.setText("");
                    ShowValues(data[i], txt_Delete);
                    break;
                }
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_I_IDDeleteKeyPressed

    private void I_IDUpdateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_I_IDUpdateKeyReleased
        // TODO add your handling code here:
        try {
            int ID = Integer.parseInt(I_IDUpdate.getText());
            for(int i = 0; i < index; i++){
                if(data[i].getID() == ID){
                    txt_Update.setText("");
                    ShowValues(data[i], txt_Update);
                    break;
                }
            }
        } catch (Exception e) {
            // TODO: handle exception
        }
    }//GEN-LAST:event_I_IDUpdateKeyReleased

    private void I_IDUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_I_IDUpdateKeyPressed
        // TODO add your handling code here:
        try {
            int ID = Integer.parseInt(I_IDUpdate.getText());
            for(int i = 0; i < index; i++){
                if(data[i].getID() == ID){
                    txt_Update.setText("");
                    ShowValues(data[i], txt_Update);
                    break;
                }
            }
        } catch (Exception e) {
            // TODO: handle exception
        }

    }//GEN-LAST:event_I_IDUpdateKeyPressed

    private void ShowValues(Employee ObjE, JTextArea txtArea){
        txtArea.append("\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
        txtArea.append("\nID: " + ObjE.getID());
        txtArea.append("\nName: " + ObjE.getName());
        txtArea.append("\nJA_DayW_47: " + ObjE.getJA_EmplTy_47());
        txtArea.append("\nDepartament: " + ObjE.getJA_WorkDep_47());
        txtArea.append("\nSection: " + ObjE.getJA_Sec_47());
        txtArea.append("\nDivision: " + ObjE.getJA_Div_47());
        txtArea.append("\nBrithDate: " + ObjE.getID());
        txtArea.append("\nDepartament: " + ObjE.getJA_BrithDep_47());
        txtArea.append("\nExpedition ID: " + ObjE.getJA_ExpID_47());
        txtArea.append("\nMunicipiality: " + ObjE.getJA_Mun_47());
        txtArea.append("\nDistrict: " + ObjE.getJA_District());
        txtArea.append("\nBlood type: " + ObjE.getJA_BloodTy_47());
        txtArea.append("\nZodiac Sign: " + ObjE.getJA_ZodiSign_47());
        txtArea.append("\nSBMA: " + ObjE.getJA_SBMA_47());
        txtArea.append("\nDays Worked: " + ObjE.getJA_DayW_47());
        txtArea.append("\nDaytime: " + ObjE.getJA_ExtrD_47());
        txtArea.append("\nNight: " + ObjE.getJA_ExtrN_47());
        txtArea.append("\nSundays: " + ObjE.getJA_ExtrS());
        txtArea.append("\nNet: " + ObjE.getJA_Net_47());
        txtArea.append("\n=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-");
        
    }



    private void ClearButtons(){
        b_Create.setBorderWidth(0);
        b_Update.setBorderWidth(0);
        b_Read.setBorderWidth(0);
        b_Delete.setBorderWidth(0);
    }

    private void SendValues(){
        //Realiza los calculos
        data[index].setJA_Age_47(ObjM.Ja_CalcAge_47(data[index].getDateTimeJA_BrithDate_47()));
        //Time value-------------------------------------------------------------------------------------------------------------------------------------
        data[index].setJA_Day_47(ObjM.JA_Day_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Fortnight_47(ObjM.JA_Fortnight_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Week_47(ObjM.JA_Week_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Bimester_47(ObjM.JA_Bimester_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Trimester_47(ObjM.JA_Trimester_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Semester_47(ObjM.JA_Semester_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Annual_47(ObjM.JA_Annual_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Quinquennium_47(ObjM.JA_Quinquennium_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Hour_47(ObjM.JA_Hour_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Minute_47(ObjM.JA_Minute_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Second_47(ObjM.JA_Second_47(data[index].getJA_SBMA_47()));
        data[index].setJA_TenthSecond_47(ObjM.JA_TenthSecond_47(data[index].getJA_SBMA_47()));
        data[index].setJA_HundredthSecond_47(ObjM.JA_HundredthSecond_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Nanosecond_47(ObjM.JA_Nanosecond_47(data[index].getJA_SBMA_47()));
        data[index].setJA_Picosecond_47(ObjM.JA_Picosecond_47(data[index].getJA_SBMA_47()));

        data[index].setJA_ExtrDVal_47(ObjM.JA_Daytime_47(data[index].getJA_WorkDep_47(), data[index].getJA_Sec_47(), data[index].getJA_Div_47(), data[index].getJA_Hour_47()));
        data[index].setJA_ExtrNVal_47(ObjM.JA_Night_47(data[index].getJA_WorkDep_47(), data[index].getJA_Sec_47(), data[index].getJA_Div_47(), data[index].getJA_Hour_47()));
        data[index].setJA_ExtrSVal_47(ObjM.JA_Sunday_57(data[index].getJA_WorkDep_47(), data[index].getJA_Sec_47(), data[index].getJA_Div_47(), data[index].getJA_Hour_47()));
        //---------------------------------------------------------------------------------------------------------------------------------------------

        //Total time value -------------------------------------------------------------------------------------------------------------
        data[index].setJA_devengadSalary_47(ObjM.JA_devengadSalary_47(data[index].getJA_DayW_47(), data[index].getJA_Day_47()));
        data[index].setJA_Daytime_47(ObjM.JA_Daytime_47(data[index].getJA_ExtrD_47(), data[index].getJA_ExtrDVal_47()));
        data[index].setJA_Nocturnal_47(ObjM.JA_Nocturnal_47(data[index].getJA_ExtrN_47(), data[index].getJA_ExtrNVal_47()));
        data[index].setJA_Sunday_47(ObjM.JA_Sundays_47(data[index].getJA_ExtrS(), data[index].getJA_ExtrSVal_47()));
        //Total segundos extra -------------->
        //Total decima de segundos extra ---->
        //Total centecima de segundos extra ->
        //Total nanosegundos extra ---------->
        //Total picosegundos extra ---------->
        //------------------------------------------------------------------------------------------------------------------------------

        //Premiums ---------------------------------------------------------------------------------------------------------------------
        data[index].setJA_Premiums_47("Jacaranda", ObjM.JA_JacarandePremium_47(data[index].getJA_ExtrD_47(), data[index].getJA_BrithDep_47(), data[index].getJA_Mun_47(), data[index].getJA_SBMA_47()));
        data[index].setJA_Premiums_47("Marcelina", ObjM.JA_MarcelinaPremium_47(data[index].getJA_Hour_47(), data[index].getJA_ExpID_47(), data[index].getJA_BloodTy_47(), data[index].getJA_ZodiSign_47(), data[index].getJA_Premiums_47("Jacaranda")));
        data[index].setJA_Premiums_47("Firicundina", ObjM.JA_FiricundinaPremium_47(data[index].getJA_EmplTy_47(), data[index].getJA_Premiums_47("Marcelina")));
        data[index].setJA_Premiums_47("Petunia", ObjM.JA_PetuniaPremium_47(data[index].getJA_Week_47(), data[index].getJA_Premiums_47("Firicundina")));
        data[index].setJA_Premiums_47("Hermenegilda", ObjM.JA_HermenegildaPremium_47(data[index].getJA_Age_47(), data[index].getJA_WorkDep_47(), data[index].getJA_Sec_47(), data[index].getJA_Div_47(), data[index].getJA_Mun_47(), data[index].getJA_BloodTy_47(), data[index].getJA_SBMA_47(), data[index].getJA_District(), data[index].getJA_Premiums_47("Jacaranda"), data[index].getJA_Premiums_47("Petunia")));
        data[index].setJA_Premiums_47("Age", ObjM.JA_AgePremium_47(data[index].getJA_Age_47(), data[index].getJA_Fortnight_47()));
        data[index].setJA_Premiums_47("Feending", ObjM.JA_FeednigPremium_47(data[index].getJA_Fortnight_47(), 800));
        data[index].setJA_Premiums_47("Production", ObjM.JA_ProductionPremium_47(data[index].getJA_WorkDep_47(), data[index].getJA_Sec_47(), data[index].getJA_Fortnight_47()));
        data[index].setJA_Premiums_47("Consanguinity", ObjM.JA_ConsanguinityPremium_47(data[index].getJA_SBMA_47(), data[index].getJA_BloodTy_47(), data[index].getJA_BrithDep_47(), data[index].getJA_Age_47(), data[index].getJA_ExtrD_47()));
        //----------------------------------------------------------------------------------------------------------------------------

        //Discounts ------------------------------------------------------------------------------------------------------------------
        data[index].setJA_Pension_47(ObjM.JA_Pension_47(data[index].getJA_SBMA_47(), 800));
        data[index].setJA_Health_47(ObjM.JA_Health_47(data[index].getJA_SBMA_47(), 800));
        data[index].setJA_Transport_47(ObjM.JA_Transport_47(800, data[index].getJA_SBMA_47()));
        //----------------------------------------------------------------------------------------------------------------------------

        //Totals ---------------------------------------------------------------------------------------------------------------------
        data[index].setJA_TPremiums_47(ObjM.TotalPrem(data[index].getAllPremiums()));
        data[index].setJA_TotalWorked_47(ObjM.JA_totalsWorked_47(data[index].getJA_devengadSalary_47(), data[index].getJA_Daytime_47(), data[index].getJA_Nocturnal_47(), data[index].getJA_Sunday_47(), data[index].getJA_Second_47(), data[index].getJA_TenthSecond_47(), data[index].getJA_HundredthSecond_47(), data[index].getJA_Nanosecond_47(), data[index].getJA_Picosecond_47()));
        data[index].setJA_Deducid_47(ObjM.JA_Deducid_47(0, data[index].getJA_Health_47(), data[index].getJA_Pension_47()));
        data[index].setJA_TotDevegad_47(ObjM.JA_TotDevegad_47(data[index].getJA_TPremiums_47(), data[index].getJA_TotalWorked_47(), data[index].getJA_Transport_47()));
        data[index].setJA_Net_47(ObjM.JA_Net_47(data[index].getJA_Deducid_47(), data[index].getJA_TotDevegad_47()));
        //----------------------------------------------------------------------------------------------------------------------------
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField E_ExpID;
    private javax.swing.JComboBox<String> I_AtributeUpdate;
    private javax.swing.JComboBox<String> I_BritDep;
    private com.toedter.calendar.JDateChooser I_BrttDa;
    private javax.swing.JTextField I_DaysW;
    private javax.swing.JComboBox<String> I_Dep;
    private javax.swing.JComboBox<String> I_Disctrict;
    private javax.swing.JComboBox<String> I_Div;
    private javax.swing.JTextField I_ExtDay;
    private javax.swing.JTextField I_ExtNig;
    private javax.swing.JTextField I_ExtSun;
    private javax.swing.JTextField I_ID;
    private javax.swing.JTextField I_IDDelete;
    private javax.swing.JTextField I_IDUpdate;
    private javax.swing.JTextField I_Mun;
    private javax.swing.JTextField I_Name;
    private javax.swing.JTextField I_Salary;
    private javax.swing.JComboBox<String> I_Sec;
    private javax.swing.JTextField I_ValueUpdate;
    private javax.swing.JComboBox<String> I_ZodSig;
    private javax.swing.JRadioButton aN;
    private javax.swing.JRadioButton aP;
    private javax.swing.JRadioButton abN;
    private javax.swing.JRadioButton abP;
    private javax.swing.JRadioButton bN;
    private javax.swing.JRadioButton bP;
    private manulibrary.buttonPanel b_Create;
    private manulibrary.buttonPanel b_Delete;
    private manulibrary.buttonPanel b_Read;
    private manulibrary.buttonPanel b_Update;
    private manulibrary.buttonPanel btn_Delete;
    private javax.swing.JButton btn_Next;
    private manulibrary.buttonPanel btn_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton oN;
    private javax.swing.JRadioButton oP;
    private javax.swing.JPanel p_Create;
    private javax.swing.JPanel p_Delete;
    private javax.swing.JPanel p_Menu;
    private javax.swing.JPanel p_Read;
    private javax.swing.JPanel p_Update;
    private javax.swing.JTabbedPane panels;
    private javax.swing.JTable tableData;
    private javax.swing.JTextArea txt_Delete;
    private javax.swing.JComboBox<String> txt_EmpTy;
    private javax.swing.JTextArea txt_Update;
    // End of variables declaration//GEN-END:variables
}
