/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author juanm
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        p_Menu = new javax.swing.JPanel();
        b_Create = new manulibrary.buttonPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        b_Read = new manulibrary.buttonPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        b_Update = new manulibrary.buttonPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        b_Delete = new manulibrary.buttonPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panels = new javax.swing.JTabbedPane();
        p_Create = new javax.swing.JPanel();
        p_Read = new javax.swing.JPanel();
        p_Update = new javax.swing.JPanel();
        p_Delete = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        p_Menu.setBackground(new java.awt.Color(44, 47, 51));
        p_Menu.setLayout(new java.awt.GridBagLayout());

        b_Create.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Create.setBorderWidth(5);
        b_Create.setCornerRadius(70);
        b_Create.setEndColor(new java.awt.Color(251, 46, 0));
        b_Create.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Create.setStartColor(new java.awt.Color(187, 0, 163));
        b_Create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_CreateMouseClicked(evt);
            }
        });
        b_Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Create");
        b_Create.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("+100 emplyees added");
        b_Create.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Create, gridBagConstraints);

        b_Read.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Read.setBorderWidth(5);
        b_Read.setCornerRadius(70);
        b_Read.setEndColor(new java.awt.Color(251, 46, 0));
        b_Read.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Read.setStartColor(new java.awt.Color(187, 0, 163));
        b_Read.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ReadMouseClicked(evt);
            }
        });
        b_Read.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Know your employees");
        b_Read.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 20));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Read");
        b_Read.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Read, gridBagConstraints);

        b_Update.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Update.setBorderWidth(5);
        b_Update.setCornerRadius(70);
        b_Update.setEndColor(new java.awt.Color(251, 46, 0));
        b_Update.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Update.setStartColor(new java.awt.Color(187, 0, 163));
        b_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_UpdateMouseClicked(evt);
            }
        });
        b_Update.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("+1000 data avalible");
        b_Update.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 200, 20));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update");
        b_Update.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 130, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Update, gridBagConstraints);

        b_Delete.setBorderColor(new java.awt.Color(204, 204, 204));
        b_Delete.setBorderWidth(5);
        b_Delete.setCornerRadius(70);
        b_Delete.setEndColor(new java.awt.Color(251, 46, 0));
        b_Delete.setPreferredSize(new java.awt.Dimension(250, 100));
        b_Delete.setStartColor(new java.awt.Color(187, 0, 163));
        b_Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_DeleteMouseClicked(evt);
            }
        });
        b_Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Delete inactive");
        b_Delete.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, 20));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Delete");
        b_Delete.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 40));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 12, 12);
        p_Menu.add(b_Delete, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Carrefurgas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 26, 0);
        p_Menu.add(jLabel1, gridBagConstraints);

        getContentPane().add(p_Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 690));

        panels.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        p_Create.setBackground(new java.awt.Color(35, 39, 42));
        p_Create.setLayout(new java.awt.GridBagLayout());
        panels.addTab("tab1", p_Create);

        p_Read.setBackground(new java.awt.Color(35, 39, 42));
        p_Read.setLayout(new java.awt.GridBagLayout());
        panels.addTab("tab2", p_Read);

        p_Update.setBackground(new java.awt.Color(35, 39, 42));
        p_Update.setLayout(new java.awt.GridBagLayout());
        panels.addTab("tab3", p_Update);

        p_Delete.setBackground(new java.awt.Color(35, 39, 42));
        p_Delete.setLayout(new java.awt.GridBagLayout());
        panels.addTab("tab4", p_Delete);

        getContentPane().add(panels, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 730, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_CreateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_CreateMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(0);
        ClearButtons();
        b_Create.setBorderWidth(5);
    }//GEN-LAST:event_b_CreateMouseClicked

    private void b_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_UpdateMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(1);
        ClearButtons();
        b_Update.setBorderWidth(5);
    }//GEN-LAST:event_b_UpdateMouseClicked

    private void b_ReadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ReadMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(2);
        ClearButtons();
        b_Read.setBorderWidth(5);
    }//GEN-LAST:event_b_ReadMouseClicked

    private void b_DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_DeleteMouseClicked
        // TODO add your handling code here:
        panels.setSelectedIndex(3);
        ClearButtons();
        b_Delete.setBorderWidth(5);
    }//GEN-LAST:event_b_DeleteMouseClicked

    private void ClearButtons(){
        b_Create.setBorderWidth(0);
        b_Update.setBorderWidth(0);
        b_Read.setBorderWidth(0);
        b_Delete.setBorderWidth(0);
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private manulibrary.buttonPanel b_Create;
    private manulibrary.buttonPanel b_Delete;
    private manulibrary.buttonPanel b_Read;
    private manulibrary.buttonPanel b_Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel p_Create;
    private javax.swing.JPanel p_Delete;
    private javax.swing.JPanel p_Menu;
    private javax.swing.JPanel p_Read;
    private javax.swing.JPanel p_Update;
    private javax.swing.JTabbedPane panels;
    // End of variables declaration//GEN-END:variables
}
